version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region ap-south-1)
  build:
    commands:
      - docker build -t youtube:latest .
      - docker tag youtube:latest 016781836113.dkr.ecr.ap-south-1.amazonaws.com/pulling-service:latest
  post_build:
    commands:
      - docker push 016781836113.dkr.ecr.ap-south-1.amazonaws.com/pulling-service:latest
      - printf '[{"name":"helloWorld","imageUri":"%s"}]' 016781836113.dkr.ecr.ap-south-1.amazonaws.com/pulling-service:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
